"""A small real BIFF8 workbook used by the XLS attachment regressions.

The source tree keeps the fixture as deterministic gzip+base64 text so it can
be reviewed and patched without relying on a binary-file tool. The decoded
bytes are the original ``.xls`` payload generated by a spreadsheet writer;
tests never need ``xlwt`` (or any other fixture-generation dependency).
"""

import base64
import gzip

_LEGACY_XLS_GZIP_BASE64 = (
    "H4sIAAAAAAAC/+1YTWgTQRT+ZpM0P6TppqZCK5SlYNW2F/Hipd0qai+1VHuwiKDbZJHSsJE1IPWg1ZqjIHhSvBR60UPViz/o"
    "QW8exIoeBEFI9OhJUPDQZn3zsiuJ9dCAlirzLfPN2zdvZt7uvJnZ2dfL6fLC/a4KfsEQQqh6cbTU6QSleHCjg8o9T4pBHqPk"
    "KfxTiMdoIFsieNL6MirHUI53BRruhZ8TAx8pncAZjBUc29hA7GcfLCF9GCQWuEWaFDrZq3bmLPMW5rts+ZR5mDVXmQfJtiyO"
    "Y9kc69vrR/Gk1sNlKch2H3Kd96zZjQ68kFF88Zqo2Uawz5228puzoDucxCJo3EZsx3atfBkZGsBFfPMM4GswU58ZSr+xegHS"
    "f2/UR3+jv66FgTl4pzjAS0jiVUiWhHHAKlor6OegrAU5Ru3TVnbWmBydMM7aTnHasfMJYMLOFpyc4RbOJeTqzLNZb5jNrRzl"
    "SeIc2lhOc5M6rdcrt7+8OTw1bp5kzRyv4LV1frt0DR4uyRpUOcUl2k/uY645eJlb3cZyF3OGIpTy3vEOXzg0zzZXuLSX+tnD"
    "eGvuqJN3klz6fORRd+mTuYvkpZHK+czSO3MBPbTv5Ki+vOYxIAbEzRsSj80gF/6a8IG5c836ENN033fP38zasIoEi2nmC1qC"
    "nz2NO7694PtGe8H2koe0djzgFzJct0cmoKCgoKCgoKCgoLB5Ifzv+RAfO0Cf67VTQ9T/r7NKqap+k/y3OIoCXUU6mB6EQ7mL"
    "2abiZysiImhLrLNO8L9Q4hj17mIGU+zHTNPxS6c+Uf88666o/7kp1Gz/1Wb8/Mv9/wBxdrdsABYAAA=="
)


def build_xls() -> bytes:
    """Return the valid legacy workbook represented by the fixture."""
    return gzip.decompress(base64.b64decode(_LEGACY_XLS_GZIP_BASE64, validate=True))
