"""Locale-aware messages generated by the Worker platform.

Only messages owned by DLR live here. Adapter output, tracebacks and output
from package tools are deliberately kept outside this translation layer.
"""

from typing import Final, Literal

WorkerLocale = Literal["zh-CN", "en"]
DEFAULT_WORKER_LOCALE: Final[WorkerLocale] = "zh-CN"

_MESSAGES: Final[dict[WorkerLocale, dict[str, str]]] = {
    "zh-CN": {
        "dependency.log_prefix": "[依赖检查]",
        "dependency.check_passed": "{dependency} 已安装，检查通过",
        "dependency.install_started": "{dependency} 未安装，开始安装",
        "dependency.install_succeeded": "{dependency} 安装成功",
        "dependency.install_failed": "{dependency} 安装失败，停止本次运行",
        "dependency.preparation_failed": "依赖准备失败，停止本次运行",
        "dependency.prepare_failed": "{language} 依赖准备失败",
        "dependency.prepare_failed_dependency": "（失败依赖：{dependency}）",
        "dependency.script_not_started": "[系统] 本次执行未开始脚本逻辑",
        "dependency.offline_cache_fallback": "[离线缓存不足，正在使用配置的依赖源重试]",
        "dependency.no_source_python": (
            "本地缓存中没有所需依赖，且未配置 Python 依赖源；请管理员在系统设置中添加依赖源"
        ),
        "dependency.no_source_javascript": (
            "本地缓存中没有所需依赖，且未配置 JavaScript 依赖源；请管理员在系统设置中添加依赖源"
        ),
        "dependency.no_source_java": (
            "本地缓存中没有所需依赖，且未配置 Java 依赖源；请管理员在系统设置中添加依赖源"
        ),
        "dependency.source_hint.dns": "依赖源域名解析失败（DNS）：请检查容器 DNS 配置",
        "dependency.source_hint.network": (
            "依赖源网络不可达：请检查容器出站网络、防火墙与代理设置后重试"
        ),
        "dependency.source_hint.tls": (
            "依赖源 TLS 握手或证书校验失败：请确认源地址证书有效，或配置可信 CA"
        ),
        "dependency.source_hint.auth": "依赖源认证失败：请检查该依赖源绑定的凭据是否正确、有效",
        "dependency.source_hint.package": (
            "包或制品不存在：请检查依赖名称与版本是否真实存在于该依赖源"
        ),
        "dependency.source_hint.source": (
            "依赖源仓库不存在或不可用：请检查仓库地址是否正确，或改用其他镜像源"
        ),
        "runtime.unsupported_language": "不支持的适配器语言：{language}",
        "runtime.unavailable": "{runtime} Runtime 不可用",
        "runtime.worker_internal_error": "Worker 执行任务时发生内部错误",
        "execution.cancelled": "取消执行",
        "execution.timed_out": "运行超时（{timeout}s）",
        "execution.process_exited": "适配器进程以退出码 {returncode} 结束",
        "execution.no_output": "适配器未生成 output.json",
        "execution.invalid_output": "output.json 无法解析：{detail}",
        "execution.resource_exceeded": "执行超出资源限制",
        "execution.output_too_large": "适配器输出超过大小限制，已保留预览",
    },
    "en": {
        "dependency.log_prefix": "[Dependency check]",
        "dependency.check_passed": "{dependency} is installed; check passed",
        "dependency.install_started": "{dependency} is not installed; starting installation",
        "dependency.install_succeeded": "{dependency} installation succeeded",
        "dependency.install_failed": "{dependency} installation failed; stopping this run",
        "dependency.preparation_failed": "Dependency preparation failed; stopping this run",
        "dependency.prepare_failed": "{language} dependency preparation failed",
        "dependency.prepare_failed_dependency": " (failed dependency: {dependency})",
        "dependency.script_not_started": "[System] The Adapter script did not start",
        "dependency.offline_cache_fallback": (
            "[Offline cache is insufficient; retrying with the configured package source]"
        ),
        "dependency.no_source_python": (
            "The required dependencies are not in the local cache and no Python dependency "
            "source is configured; ask an administrator to add one in System Settings"
        ),
        "dependency.no_source_javascript": (
            "The required dependencies are not in the local cache and no JavaScript "
            "dependency source is configured; ask an administrator to add one in System Settings"
        ),
        "dependency.no_source_java": (
            "The required dependencies are not in the local cache and no Java dependency "
            "source is configured; ask an administrator to add one in System Settings"
        ),
        "dependency.source_hint.dns": (
            "Dependency source DNS resolution failed: check the container DNS configuration"
        ),
        "dependency.source_hint.network": (
            "Dependency source is unreachable: check outbound network, firewall and proxy "
            "settings, then retry"
        ),
        "dependency.source_hint.tls": (
            "Dependency source TLS or certificate validation failed: verify the source "
            "certificate or configure a trusted CA"
        ),
        "dependency.source_hint.auth": (
            "Dependency source authentication failed: check that its bound Credential is valid"
        ),
        "dependency.source_hint.package": (
            "The package or artifact does not exist: check its name and version in the "
            "dependency source"
        ),
        "dependency.source_hint.source": (
            "The dependency source repository is unavailable: check its URL or choose "
            "another mirror"
        ),
        "runtime.unsupported_language": "Unsupported Adapter language: {language}",
        "runtime.unavailable": "{runtime} Runtime is unavailable",
        "runtime.worker_internal_error": "The Worker encountered an internal execution error",
        "execution.cancelled": "Execution cancelled",
        "execution.timed_out": "Execution timed out after {timeout}s",
        "execution.process_exited": "The Adapter process exited with code {returncode}",
        "execution.no_output": "The Adapter did not produce output.json",
        "execution.invalid_output": "output.json is invalid: {detail}",
        "execution.resource_exceeded": "The execution exceeded its resource limit",
        "execution.output_too_large": (
            "The Adapter output exceeded its size limit; a preview was retained"
        ),
    },
}

_SOURCE_HINT_CODES: Final[tuple[str, ...]] = (
    "dns",
    "network",
    "tls",
    "auth",
    "package",
    "source",
)


def resolve_locale(value: object) -> WorkerLocale:
    """Accept only the two persisted locales; malformed payloads use zh-CN."""
    if value == "en":
        return "en"
    return DEFAULT_WORKER_LOCALE


def text(locale: WorkerLocale, key: str, **params: object) -> str:
    """Render one DLR-owned message without touching arbitrary tool output."""
    template = _MESSAGES[locale].get(key) or _MESSAGES[DEFAULT_WORKER_LOCALE].get(key, key)
    return template.format(**params)


def source_hint(locale: WorkerLocale, code: str | None) -> str | None:
    """Translate one stable dependency-source diagnostic category."""
    if code not in _SOURCE_HINT_CODES:
        return None
    return text(locale, f"dependency.source_hint.{code}")


def localize_dependency_event(message: str, locale: WorkerLocale) -> str:
    """Translate known dependency event suffixes while preserving package names."""
    if locale == DEFAULT_WORKER_LOCALE:
        return message
    for suffix, key in (
        (" 已安装，检查通过", "dependency.check_passed"),
        (" 未安装，开始安装", "dependency.install_started"),
        (" 安装成功", "dependency.install_succeeded"),
        (" 安装失败，停止本次运行", "dependency.install_failed"),
    ):
        if message.endswith(suffix):
            dependency = message[: -len(suffix)]
            return text(locale, key, dependency=dependency)
    return message


def localize_dependency_log_marker(message: str, locale: WorkerLocale) -> str:
    """Translate DLR's offline retry marker, leaving tool output untouched."""
    marker = "[offline cache insufficient; retrying with the configured package source]"
    if marker in message:
        message = message.replace(marker, text(locale, "dependency.offline_cache_fallback"))
    return message
